import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Image from "next/image";
import { Bell, Home } from "lucide-react";
import Link from "next/link";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { SidebarProvider } from "@/contexts/SidebarContext";

const rubik = localFont({
  src: [
    {
      path: "../public/fonts/Rubik.ttf",
    },
  ],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${rubik.variable} antialiased`}>
      <body className="h-dvh w-dvw font-rubik text-slate-900">
        <SidebarProvider>{children}</SidebarProvider>
      </body>
    </html>
  );
}
