import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const rubik = localFont({
  src: [
    {
      path: "../public/fonts/Rubik.ttf",
    },
  ],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${rubik.variable} antialiased`}>
      <body className="h-dvh w-dvw font-rubik">
        <div className="">{children}</div>
      </body>
    </html>
  );
}
